trigger:
  branches:
    include:
      - main

stages:
- stage: Dev
  jobs:
    - job: Terraform_Dev
      steps:
        - script: ls -ltr

- stage: PreProd
  dependsOn: Dev
  condition: succeeded()
  jobs:
    - job: Terraform_PreProd
      steps:
        - script: ls -ltr

- stage: Prod
  dependsOn: PreProd
  condition: succeeded()
  jobs:
    - job: Terraform_Prod
      steps:
        - script: ls -ltr